version: '1.0.{build}'

before_build:
  - nuget restore
  
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}-rc1"

build:
  publish_nuget: true
  publish_nuget_symbols: true
  project: Telepathy.sln
  verbosity: minimal

image: Visual Studio 2017

test_script:
  - packages\OpenCover.4.6.519\tools\OpenCover.Console.exe -returntargetcode -register:user -target:"nunit3-console.exe" -targetargs:"Telepathy.Tests\bin\Debug\Telepathy.Tests.dll" -output:"coverage.xml" -filter:"+[Telepathy*]* -[Telepathy.Tests*]* "

after_test:
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f "coverage.xml" 

deploy:
  - provider: Environment
    name: nuget-telepathy
    on:
      branch: master
